#!/bin/sh

# Script that runs the HTML judge inside a container.
# 
#   - stdin: run configuration (JSON)
#   - stdout: evaluation results (JSON)
#   - stderr: should be empty
#   - exit status: should be zero

DIR="$(dirname $0)"

python3 "$DIR/runfile.py"